class VastuteqHeader extends HTMLElement {
    connectedCallback() {
        this.innerHTML =  '<header>                                                                               <a href="index.html"class="logo">                                                                       <img src="images/logo without bg.png" alt=""> </a>                                                     <nav> <ul> <li><a class="home" href="index.html">Home</a></li> <li><a class="product" href="product.html">Products</a></li>   <li><a class="service" href="#">Services</a></li>   <li><a class="vastu" href="#">Vastu</a></li>    <li><a class="about" href="#">About Us</a></li>   <li><a class="contact" href="contact.html">Contact Us</a></li> </ul>   <div class="animation start-Home"></div>  </nav></header> <br> <div class="header-line"></div><style>header   {width: 100%; background-color: #ffffff; height: 60px; position: fixed; display: flex; justify-content: space-between; z-index: 1;}   .logo img{height: 60px; width: 60px; padding-left: 30px;}   nav {background-color: #fdfcfc; height: 60px; margin-right: 5%;}   nav ul {list-style: none; padding: 20px;}   nav li {display: inline-block; padding-top: 8px; position: relative; margin-left: 20px; margin-right: 20px;}   nav a {text-decoration: none; color: #000000; position: relative; z-index: 1; transition: 0.3s ease;}   nav li a:hover,nav li a.active{color: #088178; nav li a.active::after,nav li a:hover::after{content: "";width: 40%;height: 3px;background: #088178;position: absolute;bottom: -4px;left: 20px; border-radius: 2px;}  .header-line {width: 100%;height: 2px;background-color: #000000;margin-top: 42px;}</style> ';
     }
 }


class VastuteqFooter extends HTMLElement {
    connectedCallback() {
        this.innerHTML =  '<header><a href="#" class="logo"><img src="images/logo without bg.png" alt=""></a><nav><ul><li><a class="home" href="#">Home</a></li><li><a href="product.html">Products</a></li><li><a href="#">Services</a></li><li><a href="#">Vastu</a></li><li><a href="#">About Us</a></li><li><a href="contact.html">Contact Us</a></li></ul><div class="animation start-Home"></div></nav></header><br><div class="header-line"></div> <style>footer {width: 100%;bottom: 0;margin-top: 0;background:linear-gradient(to right, #088178, #f4b466);background: #EF9C66;color: #000000;padding: 100px 0 30px;font-size: 18px;line-height:20px;align-items: baseline;}.row{ width: 80%; margin: auto; display: flex; flex-wrap: wrap; align-items: flex-start; justify-content: space-between;}.logo{height: 6rem; width: 6rem; margin-bottom: 30px;}.col h3{ width: fit-content; margin-bottom: 40px; position: relative;}.col:nth-child(2), .col:nth-child(3){flex-basis: 15%;}footer ul li{   list-style: none;   margin-bottom: 12px;}footer ul li a{   text-decoration: none;   color:#ffffff;}.col p{padding-bottom: 30px ;color: #fff;cursor: pointer;}#footer-email{width: 250px;height: 40px;border-radius:4px ;outline: none;border: none;padding-left: 0.5rem;font-size: 1rem; margin-bottom: 1rem;}#footer-email::placeholder{ color: #b1b1b1;}#footer-email-btn{ width: 100px;height: 40px; border-radius: 4px; background-color: #f94230; outline: none; border: none; color: #fff; font-size: 1rem;} #footer-email-btn:hover{     cursor: pointer; background-color: #088178; transition: all 0.4s ease;}.social-icons .bi{    padding-top: 20px;width: 30px; height: 30px; text-align: center; margin-right: 15px; cursor: pointer; display: inline-block; color: #fff;}hr{ width: 90%; border: 0;border-bottom: 1px solid #ccc; margin: 20px auto;}.copyright{ text-align: center; font-size: 16px;}.underline{ width: 100%; height: 5px; background: #d1cece; border-radius: 3px; position: absolute; top: 25px; left:0;}</style> ';
        
    }
}


customElements.define('vastuteq-header', VastuteqHeader)
customElements.define('vastuteq-footer', VastuteqFooter)
